[package]
name = "qu"
description = "quick command line programs"
version = "0.1.0"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qu-derive = { version = "0.1", path = "qu-derive" }
log = "0.4.8"
env_logger = "0.7.1"
anyhow = "1.0.26"
structopt = "0.3.9"

[workspace]
members = [
    ".",
    "qu-derive"
]
